### ISSUE TITLE
Trashed events are returned by sugar_calendar_get_events() / Event_Query()

### ISSUE THREAD

**Issue by benoitchantre** [sugarcalendar/core#120] opened 2020-09-21 16:05 UTC
Trashed events should not be returned.

**Comment by JJJ** [comment] 2020-09-29 19:08
Hey @benoitchantre. I see what you're saying.

Sugar Calendar uses `sugar_calendar_get_events()` internally, even for querying for trashed Events. It's even used inside of `sugar_calendar_delete_events()` when looping through Events to delete.

We could change it so that `status = publish` is the default, but that hasn't been necessary yet.

Is there a place in Sugar Calendar where trashed results are being returned when they should not be? Or are you thinking more along the lines of making it match the way `get_posts()` works in WordPress?

**Comment by JJJ** [comment] 2020-12-17 21:35
It may inconvenient, but this is currently by design.

Going to close this issue out. If anyone else bumps into this, I'm definitely open to adjusting the behavior, so leave your comments below! 💜

**Closed by JJJ** 2020-12-17 21:35 UTC
